/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DashBoard;

import javax.swing.JOptionPane;
import Clases.DataHolder;
import Clases.EnviarCorreo;
import Clases.SesionActual;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author SENA
 */
public class carrito extends javax.swing.JFrame {

    /**
     * Creates new form carrito
     */
    public carrito() {
        initComponents();
        // Ejemplo para cervezas
        cer1.setText("" + DataHolder.getCerPrice("Cer1"));
        cer2.setText("Cer2 - Cantidad: " + DataHolder.getCerQuantity("Cer2") + " - Precio: $" + DataHolder.getCerPrice("Cer2"));
        cer3.setText("Cer3 - Cantidad: " + DataHolder.getCerQuantity("Cer3") + " - Precio: $" + DataHolder.getCerPrice("Cer3"));
        cer4.setText("Cer4 - Cantidad: " + DataHolder.getCerQuantity("Cer4") + " - Precio: $" + DataHolder.getCerPrice("Cer4"));
        cer5.setText("Cer5 - Cantidad: " + DataHolder.getCerQuantity("Cer5") + " - Precio: $" + DataHolder.getCerPrice("Cer5"));
        cer6.setText("Cer6 - Cantidad: " + DataHolder.getCerQuantity("Cer6") + " - Precio: $" + DataHolder.getCerPrice("Cer6"));

        // Ejemplo para vinos
        vin1.setText("Vin1 - Cantidad: " + DataHolder.getVinQuantity("Vin1") + " - Precio: $" + DataHolder.getVinPrice("Vin1"));
        vin2.setText("Vin2 - Cantidad: " + DataHolder.getVinQuantity("Vin2") + " - Precio: $" + DataHolder.getVinPrice("Vin2"));
        vin3.setText("Vin3 - Cantidad: " + DataHolder.getVinQuantity("Vin3") + " - Precio: $" + DataHolder.getVinPrice("Vin3"));
        vin4.setText("Vin4 - Cantidad: " + DataHolder.getVinQuantity("Vin4") + " - Precio: $" + DataHolder.getVinPrice("Vin4"));
        vin5.setText("Vin5 - Cantidad: " + DataHolder.getVinQuantity("Vin5") + " - Precio: $" + DataHolder.getVinPrice("Vin5"));
        vin6.setText("Vin6 - Cantidad: " + DataHolder.getVinQuantity("Vin6") + " - Precio: $" + DataHolder.getVinPrice("Vin6"));

        // Ejemplo para cocteles
        coc1.setText("Coc1 - Cantidad: " + DataHolder.getCocQuantity("Coc1") + " - Precio: $" + DataHolder.getCocPrice("Coc1"));
        coc2.setText("Coc2 - Cantidad: " + DataHolder.getCocQuantity("Coc2") + " - Precio: $" + DataHolder.getCocPrice("Coc2"));
        coc3.setText("Coc3 - Cantidad: " + DataHolder.getCocQuantity("Coc3") + " - Precio: $" + DataHolder.getCocPrice("Coc3"));
        coc4.setText("Coc4 - Cantidad: " + DataHolder.getCocQuantity("Coc4") + " - Precio: $" + DataHolder.getCocPrice("Coc4"));
        coc5.setText("Coc5 - Cantidad: " + DataHolder.getCocQuantity("Coc5") + " - Precio: $" + DataHolder.getCocPrice("Coc5"));
        coc6.setText("Coc6 - Cantidad: " + DataHolder.getCocQuantity("Coc6") + " - Precio: $" + DataHolder.getCocPrice("Coc6"));
        
        can1.setText("" + DataHolder.getCerQuantity("Cer1"));

    }
    
    public JPanel getFondo() {
        return fondo;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        fondo = new javax.swing.JPanel();
        enviarButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cer1 = new javax.swing.JLabel();
        can1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cer3 = new javax.swing.JLabel();
        can3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cer5 = new javax.swing.JLabel();
        can5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cer2 = new javax.swing.JLabel();
        cer4 = new javax.swing.JLabel();
        cer6 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        can2 = new javax.swing.JLabel();
        can4 = new javax.swing.JLabel();
        can6 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        vin3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        can9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        vin1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        can7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        vin5 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        can11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vin2 = new javax.swing.JLabel();
        vin4 = new javax.swing.JLabel();
        vin6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        can8 = new javax.swing.JLabel();
        can10 = new javax.swing.JLabel();
        can12 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        coc1 = new javax.swing.JLabel();
        can13 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        coc3 = new javax.swing.JLabel();
        can15 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        coc5 = new javax.swing.JLabel();
        can17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        coc6 = new javax.swing.JLabel();
        coc2 = new javax.swing.JLabel();
        coc4 = new javax.swing.JLabel();
        can14 = new javax.swing.JLabel();
        can16 = new javax.swing.JLabel();
        can18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanel.setBackground(new java.awt.Color(141, 73, 37));
        JPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(141, 73, 37));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enviarButton.setBackground(new java.awt.Color(51, 255, 51));
        enviarButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        enviarButton.setForeground(new java.awt.Color(255, 255, 255));
        enviarButton.setText("Hacer pedido");
        enviarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enviarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enviarButtonMousePressed(evt);
            }
        });
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });
        fondo.add(enviarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Productos");
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 70, 20));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cerveza Andina light lata");
        fondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 150, 20));

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 170, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cer1.setForeground(new java.awt.Color(255, 255, 255));
        cer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cer1.setText("0");
        jPanel1.add(cer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 110, 20));

        can1.setForeground(new java.awt.Color(255, 255, 255));
        can1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        can1.setText("0");
        jPanel1.add(can1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 110, 20));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 430, 20));

        jPanel5.setBackground(new java.awt.Color(0, 170, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cerveza Miller Lite botella");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 76, 250, 20));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Cerveza Miller Lite botella");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 20));

        cer3.setForeground(new java.awt.Color(255, 255, 255));
        cer3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cer3.setText("0");
        jPanel5.add(cer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 110, 20));

        can3.setForeground(new java.awt.Color(255, 255, 255));
        can3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        can3.setText("0");
        jPanel5.add(can3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 110, 20));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 430, 20));

        jPanel6.setBackground(new java.awt.Color(0, 170, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cerveza Andina light");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 20));

        cer5.setForeground(new java.awt.Color(255, 255, 255));
        cer5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cer5.setText("0");
        jPanel6.add(cer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 110, 20));

        can5.setForeground(new java.awt.Color(255, 255, 255));
        can5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        can5.setText("0");
        jPanel6.add(can5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 110, 20));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 430, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cerveza Sol botella");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 20));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cerveza Heineken botella");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 150, 20));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cerveza Andina light botella");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 150, 20));

        cer2.setForeground(new java.awt.Color(255, 255, 255));
        cer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cer2.setText("0");
        jPanel2.add(cer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 110, 20));

        cer4.setForeground(new java.awt.Color(255, 255, 255));
        cer4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cer4.setText("0");
        jPanel2.add(cer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 110, 20));

        cer6.setForeground(new java.awt.Color(255, 255, 255));
        cer6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cer6.setText("0");
        jPanel2.add(cer6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 110, 20));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Precios");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 70, 20));

        can2.setForeground(new java.awt.Color(255, 255, 255));
        can2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        can2.setText("0");
        jPanel2.add(can2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 110, 20));

        can4.setForeground(new java.awt.Color(255, 255, 255));
        can4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        can4.setText("0");
        jPanel2.add(can4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 110, 20));

        can6.setForeground(new java.awt.Color(255, 255, 255));
        can6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        can6.setText("0");
        jPanel2.add(can6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 110, 20));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Cantidad");
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 70, 20));

        fondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 430, 140));

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 170, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vin3.setForeground(new java.awt.Color(255, 255, 255));
        vin3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vin3.setText("0");
        jPanel7.add(vin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 110, 20));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Ginebra martin miller gin ");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 20));

        can9.setForeground(new java.awt.Color(255, 255, 255));
        can9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        can9.setText("0");
        jPanel7.add(can9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 110, 20));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 430, 20));

        jPanel8.setBackground(new java.awt.Color(0, 170, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vin1.setForeground(new java.awt.Color(255, 255, 255));
        vin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vin1.setText("0");
        jPanel8.add(vin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 110, 20));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Vino tinto reserva Merlot");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 20));

        can7.setForeground(new java.awt.Color(255, 255, 255));
        can7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        can7.setText("0");
        jPanel8.add(can7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 110, 20));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 430, 20));

        jPanel9.setBackground(new java.awt.Color(0, 170, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vin5.setForeground(new java.awt.Color(255, 255, 255));
        vin5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vin5.setText("0");
        jPanel9.add(vin5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 110, 20));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Tequila gran centenario ");
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 20));

        can11.setForeground(new java.awt.Color(255, 255, 255));
        can11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        can11.setText("0");
        jPanel9.add(can11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 110, 20));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 430, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Precios");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 70, 20));

        vin2.setForeground(new java.awt.Color(255, 255, 255));
        vin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vin2.setText("0");
        jPanel3.add(vin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 110, 20));

        vin4.setForeground(new java.awt.Color(255, 255, 255));
        vin4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vin4.setText("0");
        jPanel3.add(vin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 110, 20));

        vin6.setForeground(new java.awt.Color(255, 255, 255));
        vin6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vin6.setText("0");
        jPanel3.add(vin6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 110, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Productos");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 70, 20));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tequila jose cuervo ");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 20));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Vino tinto reserva cabernet ");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 150, 20));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Vino blanco santa elena ");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 150, -1));

        can8.setForeground(new java.awt.Color(255, 255, 255));
        can8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        can8.setText("0");
        jPanel3.add(can8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 110, 20));

        can10.setForeground(new java.awt.Color(255, 255, 255));
        can10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        can10.setText("0");
        jPanel3.add(can10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 110, 20));

        can12.setForeground(new java.awt.Color(255, 255, 255));
        can12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        can12.setText("0");
        jPanel3.add(can12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 110, 20));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Cantidad");
        jPanel3.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 70, 20));

        fondo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 430, 140));

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(0, 170, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Coctel Cuba Libre");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 20));

        coc1.setForeground(new java.awt.Color(255, 255, 255));
        coc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coc1.setText("0");
        jPanel10.add(coc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 110, 20));

        can13.setForeground(new java.awt.Color(255, 255, 255));
        can13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        can13.setText("0");
        jPanel10.add(can13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 110, 20));

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 430, 20));

        jPanel11.setBackground(new java.awt.Color(0, 170, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Coctel Gin Tonic ");
        jPanel11.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 20));

        coc3.setForeground(new java.awt.Color(255, 255, 255));
        coc3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coc3.setText("0");
        jPanel11.add(coc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 110, 20));

        can15.setForeground(new java.awt.Color(255, 255, 255));
        can15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        can15.setText("0");
        jPanel11.add(can15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 110, 20));

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 430, 20));

        jPanel12.setBackground(new java.awt.Color(0, 170, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Botella de Ron Viejo ");
        jPanel12.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 20));

        coc5.setForeground(new java.awt.Color(255, 255, 255));
        coc5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coc5.setText("0");
        jPanel12.add(coc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 110, 20));

        can17.setForeground(new java.awt.Color(255, 255, 255));
        can17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        can17.setText("0");
        jPanel12.add(can17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 110, 20));

        jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 430, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Productos");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 70, 20));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Precios");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 70, 20));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Coctel Mojito ");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 20));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Coctel Daiquiri ");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 150, 20));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Gin Bosque de Indias ");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 150, 20));

        coc6.setForeground(new java.awt.Color(255, 255, 255));
        coc6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coc6.setText("0");
        jPanel4.add(coc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 110, 20));

        coc2.setForeground(new java.awt.Color(255, 255, 255));
        coc2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coc2.setText("0");
        jPanel4.add(coc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 110, 20));

        coc4.setForeground(new java.awt.Color(255, 255, 255));
        coc4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coc4.setText("0");
        jPanel4.add(coc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 110, 20));

        can14.setForeground(new java.awt.Color(255, 255, 255));
        can14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        can14.setText("0");
        jPanel4.add(can14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 110, 20));

        can16.setForeground(new java.awt.Color(255, 255, 255));
        can16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        can16.setText("0");
        jPanel4.add(can16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 110, 20));

        can18.setForeground(new java.awt.Color(255, 255, 255));
        can18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        can18.setText("0");
        jPanel4.add(can18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 110, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Cantidad");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 70, 20));

        fondo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 430, 140));

        jPanel13.setBackground(new java.awt.Color(0, 170, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Total: ");
        jPanel13.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 40));

        Total.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Total.setForeground(new java.awt.Color(255, 255, 255));
        Total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Total.setText("0");
        jPanel13.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 140, 40));

        fondo.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 430, 40));

        jPanel15.setBackground(new java.awt.Color(0, 102, 153));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cocteles");
        jPanel15.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 60));

        fondo.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 140, 60));

        jPanel14.setBackground(new java.awt.Color(0, 102, 153));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cervezas");
        jPanel14.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 60));

        fondo.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 150, 60));

        jPanel16.setBackground(new java.awt.Color(0, 102, 153));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Vinos");
        jPanel16.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 60));

        fondo.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 140, 60));

        JPanel.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String nombre = SesionActual.getNombrePersona();
            String numeroMesa = SesionActual.getNumeroMesa();

            StringBuilder cuerpo = new StringBuilder();
            cuerpo.append("<html>");
            cuerpo.append("<h2>Detalles del Pedido</h2>");
            cuerpo.append("<p><b>Nombre:</b> ").append(nombre).append("</p>");
            cuerpo.append("<p><b>Número de Mesa:</b> ").append(numeroMesa).append("</p>");
            cuerpo.append("<table border='1' cellpadding='5' cellspacing='0'>");
            cuerpo.append("<tr><th>Producto</th><th>Cantidad</th><th>Precio Unitario</th><th>Precio Total</th></tr>");
            
            // Cervezas
            cuerpo.append("<tr><td>Cerveza Andina light lata</td><td>")
                  .append(DataHolder.getCerQuantity("Cer1")).append("</td><td>")
                  .append(DataHolder.getCerPrice("Cer1")).append("</td><td>")
                  .append(DataHolder.getCerQuantity("Cer1") * DataHolder.getCerPrice("Cer1")).append("</td></tr>");
            cuerpo.append("<tr><td>Cerveza Sol botella</td><td>")
                  .append(DataHolder.getCerQuantity("Cer2")).append("</td><td>")
                  .append(DataHolder.getCerPrice("Cer2")).append("</td><td>")
                  .append(DataHolder.getCerQuantity("Cer2") * DataHolder.getCerPrice("Cer2")).append("</td></tr>");
            cuerpo.append("<tr><td>Cerveza Miller Lite botella</td><td>")
                  .append(DataHolder.getCerQuantity("Cer3")).append("</td><td>")
                  .append(DataHolder.getCerPrice("Cer3")).append("</td><td>")
                  .append(DataHolder.getCerQuantity("Cer3") * DataHolder.getCerPrice("Cer3")).append("</td></tr>");
            cuerpo.append("<tr><td>Cerveza Andina light botella</td><td>")
                  .append(DataHolder.getCerQuantity("Cer4")).append("</td><td>")
                  .append(DataHolder.getCerPrice("Cer4")).append("</td><td>")
                  .append(DataHolder.getCerQuantity("Cer4") * DataHolder.getCerPrice("Cer4")).append("</td></tr>");
            cuerpo.append("<tr><td>Cerveza Andina light</td><td>")
                  .append(DataHolder.getCerQuantity("Cer5")).append("</td><td>")
                  .append(DataHolder.getCerPrice("Cer5")).append("</td><td>")
                  .append(DataHolder.getCerQuantity("Cer5") * DataHolder.getCerPrice("Cer5")).append("</td></tr>");
            cuerpo.append("<tr><td>Cerveza Heineken botella</td><td>")
                  .append(DataHolder.getCerQuantity("Cer6")).append("</td><td>")
                  .append(DataHolder.getCerPrice("Cer6")).append("</td><td>")
                  .append(DataHolder.getCerQuantity("Cer6") * DataHolder.getCerPrice("Cer6")).append("</td></tr>");
            
            // Vinos
            cuerpo.append("<tr><td>Vino tinto reserva Merlot</td><td>")
                  .append(DataHolder.getVinQuantity("Vin1")).append("</td><td>")
                  .append(DataHolder.getVinPrice("Vin1")).append("</td><td>")
                  .append(DataHolder.getVinQuantity("Vin1") * DataHolder.getVinPrice("Vin1")).append("</td></tr>");
            cuerpo.append("<tr><td>Tequila jose cuervo</td><td>")
                  .append(DataHolder.getVinQuantity("Vin2")).append("</td><td>")
                  .append(DataHolder.getVinPrice("Vin2")).append("</td><td>")
                  .append(DataHolder.getVinQuantity("Vin2") * DataHolder.getVinPrice("Vin2")).append("</td></tr>");
            cuerpo.append("<tr><td>Ginebra martin miller gin</td><td>")
                  .append(DataHolder.getVinQuantity("Vin3")).append("</td><td>")
                  .append(DataHolder.getVinPrice("Vin3")).append("</td><td>")
                  .append(DataHolder.getVinQuantity("Vin3") * DataHolder.getVinPrice("Vin3")).append("</td></tr>");
            cuerpo.append("<tr><td>Vino tinto reserva cabernet</td><td>")
                  .append(DataHolder.getVinQuantity("Vin4")).append("</td><td>")
                  .append(DataHolder.getVinPrice("Vin4")).append("</td><td>")
                  .append(DataHolder.getVinQuantity("Vin4") * DataHolder.getVinPrice("Vin4")).append("</td></tr>");
            cuerpo.append("<tr><td>Tequila gran centenario</td><td>")
                  .append(DataHolder.getVinQuantity("Vin5")).append("</td><td>")
                  .append(DataHolder.getVinPrice("Vin5")).append("</td><td>")
                  .append(DataHolder.getVinQuantity("Vin5") * DataHolder.getVinPrice("Vin5")).append("</td></tr>");
            cuerpo.append("<tr><td>Vino blanco santa elena</td><td>")
                  .append(DataHolder.getVinQuantity("Vin6")).append("</td><td>")
                  .append(DataHolder.getVinPrice("Vin6")).append("</td><td>")
                  .append(DataHolder.getVinQuantity("Vin6") * DataHolder.getVinPrice("Vin6")).append("</td></tr>");
            
            // Cocteles
            cuerpo.append("<tr><td>Coctel Cuba Libre</td><td>")
                  .append(DataHolder.getCocQuantity("Coc1")).append("</td><td>")
                  .append(DataHolder.getCocPrice("Coc1")).append("</td><td>")
                  .append(DataHolder.getCocQuantity("Coc1") * DataHolder.getCocPrice("Coc1")).append("</td></tr>");
            cuerpo.append("<tr><td>Coctel Mojito</td><td>")
                  .append(DataHolder.getCocQuantity("Coc2")).append("</td><td>")
                  .append(DataHolder.getCocPrice("Coc2")).append("</td><td>")
                  .append(DataHolder.getCocQuantity("Coc2") * DataHolder.getCocPrice("Coc2")).append("</td></tr>");
            cuerpo.append("<tr><td>Coctel Gin Tonic</td><td>")
                  .append(DataHolder.getCocQuantity("Coc3")).append("</td><td>")
                  .append(DataHolder.getCocPrice("Coc3")).append("</td><td>")
                  .append(DataHolder.getCocQuantity("Coc3") * DataHolder.getCocPrice("Coc3")).append("</td></tr>");
            cuerpo.append("<tr><td>Coctel Daiquiri</td><td>")
                  .append(DataHolder.getCocQuantity("Coc4")).append("</td><td>")
                  .append(DataHolder.getCocPrice("Coc4")).append("</td><td>")
                  .append(DataHolder.getCocQuantity("Coc4") * DataHolder.getCocPrice("Coc4")).append("</td></tr>");
            cuerpo.append("<tr><td>Botella de Ron Viejo</td><td>")
                  .append(DataHolder.getCocQuantity("Coc5")).append("</td><td>")
                  .append(DataHolder.getCocPrice("Coc5")).append("</td><td>")
                  .append(DataHolder.getCocQuantity("Coc5") * DataHolder.getCocPrice("Coc5")).append("</td></tr>");
            cuerpo.append("<tr><td>Gin Bosque de Indias</td><td>")
                  .append(DataHolder.getCocQuantity("Coc6")).append("</td><td>")
                  .append(DataHolder.getCocPrice("Coc6")).append("</td><td>")
                  .append(DataHolder.getCocQuantity("Coc6") * DataHolder.getCocPrice("Coc6")).append("</td></tr>");
            
            // Total general
            cuerpo.append("<tr><td colspan='3'><b>Total</b></td><td>").append(Total.getText()).append("</td></tr>");
            
            cuerpo.append("</table>");
            cuerpo.append("</html>");

            EnviarCorreo.enviarCorreo("yormancaballero781@gmail.com", "Detalles del Pedido", cuerpo.toString());

            JOptionPane.showMessageDialog(null, "Correo enviado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.println("Error al enviar el correo: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error al enviar el correo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
});
    }//GEN-LAST:event_enviarButtonActionPerformed

    private void enviarButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarButtonMousePressed
        
    }//GEN-LAST:event_enviarButtonMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new carrito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel can1;
    private javax.swing.JLabel can10;
    private javax.swing.JLabel can11;
    private javax.swing.JLabel can12;
    private javax.swing.JLabel can13;
    private javax.swing.JLabel can14;
    private javax.swing.JLabel can15;
    private javax.swing.JLabel can16;
    private javax.swing.JLabel can17;
    private javax.swing.JLabel can18;
    private javax.swing.JLabel can2;
    private javax.swing.JLabel can3;
    private javax.swing.JLabel can4;
    private javax.swing.JLabel can5;
    private javax.swing.JLabel can6;
    private javax.swing.JLabel can7;
    private javax.swing.JLabel can8;
    private javax.swing.JLabel can9;
    private javax.swing.JLabel cer1;
    private javax.swing.JLabel cer2;
    private javax.swing.JLabel cer3;
    private javax.swing.JLabel cer4;
    private javax.swing.JLabel cer5;
    private javax.swing.JLabel cer6;
    private javax.swing.JLabel coc1;
    private javax.swing.JLabel coc2;
    private javax.swing.JLabel coc3;
    private javax.swing.JLabel coc4;
    private javax.swing.JLabel coc5;
    private javax.swing.JLabel coc6;
    private javax.swing.JButton enviarButton;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel vin1;
    private javax.swing.JLabel vin2;
    private javax.swing.JLabel vin3;
    private javax.swing.JLabel vin4;
    private javax.swing.JLabel vin5;
    private javax.swing.JLabel vin6;
    // End of variables declaration//GEN-END:variables
}
